---
# This playbook deploys the whole application stack in this site.

# Configure and deploy database servers.
- hosts: dbservers
  user: ubuntu
  sudo: True
  roles:
  - common
  - db

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers
  user: ubuntu
  sudo: True
  roles:
  - common
  - base-apache
  - web