---
# This role contains common plays that will run on all nodes.

- name: Update all packages to the latest
  apt: update_cache=yes cache_valid_time=3600

- name: Install common tools
  apt: pkg={{ item }} state=present
  with_items:
    - vim